name: Pre-merge checks
on: [push]
jobs:
  ui-code-checks:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    steps:    
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - working-directory: ./client
      - run: npm ci
      - run: npm run check-types
      - run: npm run test
